import { query } from '../db/connection.js';

interface AuditEntry {
  userId: number | null;
  action: string;
  projectKey?: string | null;
  ghKey?: string | null;
  detail?: Record<string, unknown>;
}

export function logAudit(entry: AuditEntry): void {
  query(
    `INSERT INTO audit_log (user_id, action, project_key, gh_key, detail_json)
     VALUES ($1, $2, $3, $4, $5)`,
    [
      entry.userId,
      entry.action,
      entry.projectKey ?? null,
      entry.ghKey ?? null,
      JSON.stringify(entry.detail ?? {}),
    ]
  ).catch((error) => {
    console.error('Failed to write audit log:', error);
  });
}

export const AuditActions = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ENABLED: 'USER_ENABLED',
  USER_DELETED: 'USER_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  PROJECT_ACCESS_GRANTED: 'PROJECT_ACCESS_GRANTED',
  PROJECT_ACCESS_REVOKED: 'PROJECT_ACCESS_REVOKED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  GREENHOUSE_CREATED: 'GREENHOUSE_CREATED',
  GREENHOUSE_UPDATED: 'GREENHOUSE_UPDATED',
  GREENHOUSE_DELETED: 'GREENHOUSE_DELETED',
  DEVICE_LINKED: 'DEVICE_LINKED',
  DEVICE_UNLINKED: 'DEVICE_UNLINKED',
  RPC_SENT: 'RPC_SENT',
  RPC_SUCCESS: 'RPC_SUCCESS',
  RPC_FAILED: 'RPC_FAILED',
  RPC_TIMEOUT: 'RPC_TIMEOUT',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  LINE_NOTIFY_UPDATED: 'LINE_NOTIFY_UPDATED',
  LINE_NOTIFY_TEST: 'LINE_NOTIFY_TEST',
  REPORT_GENERATED: 'REPORT_GENERATED',
  SENSOR_CREATED: 'SENSOR_CREATED',
  SENSOR_UPDATED: 'SENSOR_UPDATED',
  SENSOR_DELETED: 'SENSOR_DELETED',
  SENSOR_CALIBRATED: 'SENSOR_CALIBRATED',
  SENSORS_BULK_CREATED: 'SENSORS_BULK_CREATED',
  CONTROL_CREATED: 'CONTROL_CREATED',
  CONTROL_UPDATED: 'CONTROL_UPDATED',
  CONTROL_DELETED: 'CONTROL_DELETED',
  CONTROLS_BULK_CREATED: 'CONTROLS_BULK_CREATED',
  ALERT_ACKNOWLEDGED: 'ALERT_ACKNOWLEDGED',
  ALERTS_ACKNOWLEDGED_ALL: 'ALERTS_ACKNOWLEDGED_ALL',
  DATA_EXPORTED: 'DATA_EXPORTED',
};